//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@interface NewsFlowItemFactory : NSObject
{
}

+ (void)syncItemInfo:(id)arg1 toItem:(id)arg2;
+ (id)updateWeMediaInfo:(id)arg1 withPageInfo:(id)arg2;
+ (id)weMediaInfoWithPageInfo:(id)arg1;
+ (id)itemWithNewsReaderPageInfo:(id)arg1 pageUrl:(id)arg2 title:(id)arg3 picture:(id)arg4;
+ (id)itemWithData:(id)arg1 withStateTable:(id)arg2;
+ (id)itemWithData:(id)arg1 withStateTable:(id)arg2 styleTyle:(long long)arg3;

@end

